### ISSUE TITLE
WASI Build

### ISSUE THREAD

**Issue by hostilefork** [Oldes/Rebol3#48]
I don't know if this interests you, but it might:

  https://github.com/metaeducation/ren-c/runs/7140995235?check_suite_focus=true#step:18:4

Building a .wasm file against WASI means it can execute inside runtimes like WasmEdge, Wasmer, or Wasmtime.  These runtimes can do console I/O and are getting more capabilites over time...like file and network access (though the syscalls they implement are different from POSIX).  But they are being standardized, and one could potentially give out a single %r3.wasm file and be run on desktop Linux, Windows, Mac... or in the cloud, etc.

There are two toolchains that can be used for this.  One is emscripten's emcc in STANDALONE_WEBASSEMBLY mode.  This has some drawbacks, for instance you will find that things like fopen() do not work...even though the WASI runtimes have the ability to do that:

  https://v8.dev/blog/emscripten-standalone-wasm

The other is called wasi-sdk, and it has some releases here:

  https://github.com/WebAssembly/wasi-sdk/releases

Unfortunately wasi-sdk does not currently have network support, even though WASI itself is starting to have the ability (and Rust's parallel to libc supports it, while wasi-sdk's libc does not).  But this is a presumably temporary condition, as the network WASI stuff just started happening this year.

You'll have to remove setjmp()/longjmp() bits when you compile.  There is no support for this on WASI (the way emscripten supports it is by using the browser's try {} catch {} Javascript under the hood, but with WASI there's no browser and no JavaScript).  There is exception support in Wasm and it will be coming to the runtime, so Ren-C has a compile switch to use either setjmp/longjmp or try/catch.

Anyway, to build with the wasi-sdk you just get the compiler for your platform, then the sysroot file with the headers and libs for the runtime.  You say `--sysroot` and give it the path to where you unpacked the sysroot.  Things are missing and you'll have to avoid building the things that aren't there, or make stubs.

If you try to run in wasmedge without optimizing it will be slow.  (The compiler optimization settings do not optimize for particular runtimes.)  But if you use wasmedgec to optimize the executable I saw it be about 50% slower than a native optimized binary.  e.g. would take 1.5 seconds to do something an -O2 native could do in 1.  Which isn't terrible, considering the benefits and sandboxing.

Anyway, thought you might want to check it out. 🤷 

[Forum post about why I think this is notable.](https://forum.rebol.info/t/ren-c-is-now-on-the-clouds-with-wasi/1854)

**Comment by Oldes** [comment]
Hi, to be honest, I am probably some sort of _ignoramus_.

To be clear for everyone, I have no use to run Rebol in a browser nor in the WASI, which I never heard before. As an old-schooler I will stay on the ground and will continue using Rebol as a tool locally and on my servers. There is still a lot of work for me ahead.

But thank you for the info and congrats to your achievements!

**Comment by Oldes** [comment]
Also... old Rebol's goal was a [fight against software complexity](http://www.rebol.com/article/0497.html). I'm really not sure if being able to run Rebol in another complex layer (even it may looks trendy and cool) is on trail with the goal.

And the software complexity pollution mentioned in the old linked Carl's blog post is still actual. I really would like to have my server without all unnecessary dependencies. Like Python3, which I unfortunately had to install recently with Let’s Encrypt's Certbot, because I haven't enough time yet to write my own _Certbot_ in pure Rebol.

**Comment by hostilefork** [comment]
>  I am probably some sort of ignoramus.

No comment.  :-)

Okay, well yes... comment.  Complexity is always relative to a medium.  Red wanted to write very directly to 32-bit x86 code.  Now they are stuck because with new chips that medium is obsolete.  Someone wanting to run Red on an Apple Silicon ARM machine needs to install some docker image, someone wanting to run on 64-bit Linux needs to sudo-apt-get some x86 emulation packages, etc.

Or think about what happened with ChromeOS.  You can say *"oh running in the browser that's so big and fat, I want to run direct on...Windows"*.  But then Google went and ripped out all the hairiness of those layers and made the browser fundamental, on a machine that boots way faster without the legacy:

https://www.youtube.com/watch?v=DxCMwzgimBQ

So what needs a layer today might have fewer layers tomorrow.  So long as your program is in C, things like this just give you more options.

**Comment by Oldes** [comment]
You know that this is not Red repository, but thank you for an example. I know pretty well Red's weaknesses.

My opinion is, that when I want to produce a creative content using a Rebol tool, I want to do it on the device which I have under my hands and not somewhere in trendy Cloud. And if I have own Linux server I want to use power of the same Rebol tool to manage it. I simply don't have any WASI use now, but still have a lot to do to improve parts, which I daily use.

Regarding ChromeOS, I'm ignoramus again. One of my children have a device with it, because when he takes it to school, nobody want to steal it. But I don't say that I would not support it, when I find some use, which I don't have now again. It is just a locked 64bit Android running on Intel CPU anyway.

**Comment by Oldes** [comment]
And as [this Richard Feynman's thread](https://twitter.com/ProfFeynman/status/1543198066773467137?s=20&t=wDvlg5MKMqHbgrtNXRlWKg) jumped at me a few hours ago from his graveyard:

• Study hard.
• What others think of you is none of your business.
• It's OK not to have all the answers.
• Experiment, Fail, Learn and Repeat.
• Knowledge comes from experience.
• Imagination is important.
• **Do what interests you the most.**
• Stay curious

**Comment by hostilefork** [comment]
> You know that this is not Red repository, but thank you for an example. 

https://examples.yourdictionary.com/analogy-ex.html
