### ISSUE TITLE
import does not support join

### ISSUE THREAD

**Issue by fvanzeveren** [Oldes/Rebol3#68]
Hello Oldes

I do not know if it is a bug, but I find it is a very strange behaviour.

When I want to import a module (e.g. sqlite3.rebx), it works fine if I write `sqlite: import %path/to/sqlite3.rebx`, but fails when I use 'join like this `sqlite: import join library-path %sqlite3.rebx` where `library-path` is set to the folder path where sqlite3.rebx resides.
I get the following error: `** access error: cannot open: join reason: "module not found"`

Regards

François

**Comment by Oldes** [comment]
It was done by design https://github.com/Oldes/Rebol3/commit/bd09ce0ed5ab3a4b4aa9ce6312b6406d5e096599 so one can use just `import json`, when the module _exists in a searchable path_ (`system/options/module-paths`) or is _delayed_ like the JSON I used as an example.

If you need expression, use: `sqlite: import (join library-path %sqlite3.rebx)`
